version: "3"
services:
    elasticsearch:
        image: elasticsearch:7.11.2
        container_name: elasticsearch
        hostname: elasticsearch
        environment: 
          - xpack.security.enabled=true
          - xpack.security.audit.enabled=true
          - ELASTIC_PASSWORD=elastic
          - "discovery.type=single-node"
        ports:
          - 9200:9200
          - 9300:9300
        networks:
          - elknetwork
    kibana:
        image: kibana:7.11.2
        container_name: kibana
        hostname: kibana
        environment: 
          - ELASTICSEARCH_URL=http://elasticsearch:9200
          - ELASTICSEARCH_USERNAME=elastic
          - ELASTICSEARCH_PASSWORD=elastic
        ports:
          - 5601:5601
        depends_on:
          - elasticsearch
        networks:
          - elknetwork
    logstash:
        image: logstash:7.11.2
        container_name: logstash
        hostname: logstash
        ports:
          - 9600:9600
          - 5300:5300
        volumes:
          - ./config/logstashyml/logstash.yml:/usr/share/logstash/config/logstash.yml
          - ./config/logstash:/usr/share/logstash/pipeline/   
        depends_on:
          - elasticsearch
        networks:
          - elknetwork
networks:
  elknetwork:
      driver: bridge          
          


